FROM ubuntu:18.04
ARG UID
ARG GID
RUN echo "Group ID: $GID"
RUN echo "User ID: $UID"

USER root
RUN apt-get update -y && apt-get install apt-utils -y
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

# Install basic packages 
RUN apt-get upgrade -y 
RUN apt-get update -y \
    && apt-get install -y libgmp-dev python3 python3-pip g++ \
                          clang llvm lld clang-tidy clang-format \
                          gcc cmake sudo wget vim \
                          curl tmux git bc gcc-6 g++-6

# Install dependencies
RUN apt-get update -y \
    && apt-get install -y autoconf automake libtool pkg-config \
                          clang bison cmake mercurial ninja-build \
                          samba flex texinfo time libglib2.0-dev \
                          libpixman-1-dev libarchive-dev libarchive-tools \
                          libbz2-dev libattr1-dev libcap-ng-dev \
                          libexpat1-dev libgmp-dev \
                          build-essential xutils-dev bison \
                          zlib1g-dev flex libglu1-mesa-dev \
                          libxi-dev libxmu-dev freeglut3-dev \
                          libglew-dev

# Append any packages you need here
# RUN apt-get update -y \
#     && apt-get install -y ...

CMD ["bash"]

# Add dev-user
RUN groupadd -o -g $GID dev-user
RUN useradd -r -g $GID -u $UID -m -d /home/dev-user -s /sbin/nologin -c "User" dev-user
RUN echo "dev-user     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER dev-user

# Install Python packages 
ENV PATH="${PATH}:/home/dev-user/.local/bin"
RUN pip3 install --user --upgrade pip \
    && pip3 install black colorlog toml tabulate isort

# Use GCC 6
RUN mkdir /home/dev-user/scripts
RUN ln -s /usr/bin/gcc-6 /home/dev-user/scripts/gcc
RUN ln -s /usr/bin/g++-6 /home/dev-user/scripts/g++
ENV PATH="/home/dev-user/scripts/:${PATH}"

# Install CUDA
RUN cd /home/dev-user/ \
    && wget https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda_9.1.85_387.26_linux
RUN sh /home/dev-user/cuda_9.1.85_387.26_linux --silent --toolkit --toolkitpath=/home/dev-user/cuda-9.1 --tmpdir=/home/dev-user/
RUN rm -f /home/dev-user/cuda_9.1.85_387.26_linux /home/dev-user/cuda*.log

# Build GPGPUSim
RUN cd /home/dev-user \
    && git clone https://github.com/gpgpu-sim/gpgpu-sim_distribution
RUN bash -c "cd /home/dev-user/gpgpu-sim_distribution \
    && export CUDA_INSTALL_PATH=/home/dev-user/cuda-9.1/ \
    && git checkout 90ec3399763d7c8512cfe7dc193473086c38ca38 \
    && source setup_environment \
    && make"

# Add environment variables
RUN printf "\
\nexport LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:\$LIBRARY_PATH \
\n# Basic PATH setup \
\nexport PATH=/home/dev-user/scripts:/home/dev-user/.local/bin:/home/dev-user/cuda-9.1/bin:\$PATH \
\nexport CUDA_INSTALL_PATH=/home/dev-user/cuda-9.1/ \
\nsource /home/dev-user/gpgpu-sim_distribution/setup_environment \
\n# Thread setup \
\nexport nproc=\$(grep -c ^processor /proc/cpuinfo) \
\n# Terminal color... \
\nexport PS1=\"[\\\\\\[\$(tput setaf 3)\\\\\\]\\\t\\\\\\[\$(tput setaf 2)\\\\\\] \\\u\\\\\\[\$(tput sgr0)\\\\\\]@\\\\\\[\$(tput setaf 2)\\\\\\]\\\h \\\\\\[\$(tput setaf 7)\\\\\\]\\\w \\\\\\[\$(tput sgr0)\\\\\\]] \\\\\\[\$(tput setaf 6)\\\\\\]$ \\\\\\[\$(tput sgr0)\\\\\\]\" \
\nexport LS_COLORS='rs=0:di=01;96:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01' \
\nalias ls='ls --color' \
\nalias grep='grep --color'\n" >> /home/dev-user/.bashrc

# Add vim environment
RUN printf "\
\nset autoread \
\nautocmd BufWritePost *.cpp silent! !clang-format -i <afile> \
\nautocmd BufWritePost *.c   silent! !clang-format -i <afile> \
\nautocmd BufWritePost *.h   silent! !clang-format -i <afile> \
\nautocmd BufWritePost *.hpp silent! !clang-format -i <afile> \
\nautocmd BufWritePost *.cc  silent! !clang-format -i <afile> \
\nautocmd BufWritePost *.py  silent! set tabstop=4 shiftwidth=4 expandtab \
\nautocmd BufWritePost *.py  silent! !python3 -m black <afile> \
\nautocmd BufWritePost *.py  silent! !isort <afile> \
\nautocmd BufWritePost *.sv  silent! !verible-verilog-format --inplace <afile> \
\nautocmd BufWritePost *.v  silent! !verible-verilog-format --inplace <afile> \
\nautocmd BufWritePost * redraw! \
\n" >> /home/dev-user/.vimrc

# Entrypoint set up
WORKDIR workspace
